function Test:FR:SpecializedIntentions__DescribeVariation_base()
--> local NlgConstant || NlgApplication intentionAsConcept
--> domains Void
--> testSuiteId TestSuite:SpecializedIntentions_fr
--> unitTest false
--> isIntentionTest true
--> description "Check the text generated by the DescribeVariation intention."
--> action
{
    TEXT_PARAM_CONTEXT.kBLanguage = LANG_fr;
    LibDocument:Test:buildIntentionForExecution(
        DESCRIBE_VARIATION__COST,
        _EXPECTED_OUTPUTS: {
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018"
        }
    );
};

function Test:FR:SpecializedIntentions__DescribeVariationContributors_base()
--> local NlgConstant || NlgApplication intentionAsConcept
--> domains Void
--> testSuiteId TestSuite:SpecializedIntentions_fr
--> unitTest false
--> isIntentionTest true
--> description "Check the text generated by the DescribeVariationContributors intention."
--> action
{
    TEXT_PARAM_CONTEXT.kBLanguage = LANG_fr;
    LibDocument:Test:buildIntentionForExecution(
        DESCRIBE_VARIATION_CONTRIBUTORS__COST,
        _EXPECTED_OUTPUTS: {
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018"
        }
    );
};

function Test:FR:SpecializedIntentions__DescribeVariationContributors_DescribeVariationThreeContributorsBullet()
--> local NlgConstant || NlgApplication intentionAsConcept
--> domains Void
--> testSuiteId TestSuite:SpecializedIntentions_fr
--> unitTest false
--> isIntentionTest true
--> description "Check the text generated by the DescribeVariationThreeContributorsBullet intention."
--> action
{
    TEXT_PARAM_CONTEXT.kBLanguage = LANG_fr;
    LibDocument:Test:buildIntentionForExecution(
        DESCRIBE_VARIATION_THREE_CONTRIBUTORS_BULLET__COST,
        _EXPECTED_OUTPUTS: {
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes enregistrent une baisse de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont baissé de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont chuté de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes ont diminué de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes sont en baisse de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, finissant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, s'établissant à 5 K$ en 2018",
            "Les charges externes sont en retrait de 33,3 % par rapport à 2016, terminant à 5 K$ en 2018"
        }
    );
};
