function Test:EN:SpecializedIntentions__DescribeVariation_base()
--> local NlgConstant || NlgApplication intentionAsConcept
--> domains Void
--> testSuiteId TestSuite:SpecializedIntentions_en
--> unitTest false
--> isIntentionTest true
--> description "Check the text generated by the DescribeVariation intention."
--> action
{
    TEXT_PARAM_CONTEXT.kBLanguage = LANG_en;
    LibDocument:Test:buildIntentionForExecution(
        DESCRIBE_VARIATION__COST,
        _EXPECTED_OUTPUTS: {
            "Administrative expenses declined (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses declined by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses decreased (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses decreased by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses dropped (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses dropped by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses fell (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses fell by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses went down (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses went down by 33.3% since 2016, finishing at $5K in 2018"
        }
    );
};

function Test:EN:SpecializedIntentions__DescribeVariationContributors_base()
--> local NlgConstant || NlgApplication intentionAsConcept
--> domains Void
--> testSuiteId TestSuite:SpecializedIntentions_en
--> unitTest false
--> isIntentionTest true
--> description "Check the text generated by the DescribeVariationContributors intention."
--> action
{
    TEXT_PARAM_CONTEXT.kBLanguage = LANG_en;
    LibDocument:Test:buildIntentionForExecution(
        DESCRIBE_VARIATION_CONTRIBUTORS__COST,
        _EXPECTED_OUTPUTS: {
            "Administrative expenses declined (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses declined by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses decreased (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses decreased by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses dropped (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses dropped by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses fell (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses fell by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses went down (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses went down by 33.3% since 2016, finishing at $5K in 2018"
        }
    );
};

function Test:EN:SpecializedIntentions__DescribeVariationContributors_DescribeVariationThreeContributorsBullet()
--> local NlgConstant || NlgApplication intentionAsConcept
--> domains Void
--> testSuiteId TestSuite:SpecializedIntentions_en
--> unitTest false
--> isIntentionTest true
--> description "Check the text generated by the DescribeVariationThreeContributorsBullet intention."
--> action
{
    TEXT_PARAM_CONTEXT.kBLanguage = LANG_en;
    LibDocument:Test:buildIntentionForExecution(
        DESCRIBE_VARIATION_THREE_CONTRIBUTORS_BULLET__COST,
        _EXPECTED_OUTPUTS: {
            "Administrative expenses declined (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses declined by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses decreased (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses decreased by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses dropped (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses dropped by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses fell (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses fell by 33.3% since 2016, finishing at $5K in 2018",
            "Administrative expenses went down (33.3% since 2016), finishing at $5K in 2018",
            "Administrative expenses went down by 33.3% since 2016, finishing at $5K in 2018"
        }
    );
};
